### ISSUE TITLE
Doesn't drop viewdistance

### ISSUE THREAD

**Issue by Decme** [Kugge/BestViewDistance#1]
Version: 3.5-SNAPSHOT
Environment: Paperspigot

Scenario: max view distance set to 16, minimum 7. Had roughly 7 players online, and tps stared tanking, dropping as low as 11. Using /view <player> the output stated that viewdistance was dropping for each player including myself, however when I went to a high place, it was obvious that my own viewdistance was still 16, as I could see very far, same as when 1 - 3 players were on and all our viewdistance were still at 16. Before adding this plugin to the server, I've had 15+ players online with viewdistance hardcoded to 9 in the spigot jar, and tps never went as low as 11.

Is it unloading already unloaded chunks? If not, is this possible?

**Comment by Lxct** [comment]
Can you send timings and your config.yml ?
Also, 1.13 or 1.12.2 ? Which build of paper ?

Btw, "PaperSpigot" is now called "Paper"

**Comment by Decme** [comment]
My config.yml is empty. I was on 1.13.2 on build 403, now updated to build 426. Yes I know it's now just called Paper but I've gotten into the habit of calling it Paperspigot outside the Paper community as not everyone knows what Paper is.

The timings reports seem to contain server-specific information so I'm wary of posting those.

**Comment by Lxct** [comment]
Your config.yml is empty ?
About paper timings, you can hide whatever you want in paper.yml : 
```timings: 
  enabled: true
  verbose: true
  server-name-privacy: false # <= true if you didn't want to show your saver motd and name
  hidden-config-entries:
 # - anything, plugin, and so on...
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
```
I just want to see your config inside spigot.yml, bukkit.yml and paper.yml, mob spawning rate and view distance.

**Comment by Decme** [comment]
Got it, will keep an eye and post if I get the tps drop again, along with the bukkit/spigot/paper yml files. (Less players online today.)

**Comment by Lxct** [comment]
About the `BestViewDistance/config.yml`, if you can paste it here too

**Comment by Lxct** [comment]
This ticket will be closed if there are no more details.
