### ISSUE TITLE
BestViewDistance::Task: me.lxct.bestviewdistance.functions.sync.SetViewDistance (Single)

### ISSUE THREAD

**Issue by TomLewis** [Kugge/BestViewDistance#10]
`BestViewDistance::Task: me.lxct.bestviewdistance.functions.sync.SetViewDistance (Single)`

![Screenshot 2019-03-24 18 05 25](https://user-images.githubusercontent.com/144046/54883629-86169f80-4e5f-11e9-9671-91f4094f7711.png)

Causing massive lag spike.

 git-Paper-1606 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
BVD: 11.9

**Comment by sofianedjerbi** [comment]
It's absolutely normal. However, you should tweak config file in order to reduce changing view distance.
Please try out the latest dev build.
