### ISSUE TITLE
Option to hook into EssentialsX for AFK view distance.

### ISSUE THREAD

**Issue by mibby** [Kugge/BestViewDistance#11]
Would it be possible to hook into EssentialsX to get AFK status for the AFK view distance? Would help with performance a little bit since you wouldn't need to tick each player separately with ``AFKDelay``.

**Comment by graywolf336** [comment]
Does EssentialsX fire an event when a player goes afk?

**Comment by mibby** [comment]
I'm not 100% sure, but I have other plugins that detect and hook into Essentials when players go AFK.

Edit: i.e. https://github.com/CodeCrafter47/BungeeTabListPlus/blob/c14a6400393a6e4e39ab91ffa527fbafdd22df99/bungee/src/main/java/codecrafter47/bungeetablistplus/playersorting/rules/AFKLast.java#L31

**Comment by graywolf336** [comment]
https://github.com/graywolf336/TrailingPerspective/blob/master/src/main/java/com/graywolf336/trailingperspective/hooks/EssentialsHook.java#L32

It does and I've used it before 😂

**Comment by sofianedjerbi** [comment]
This is useless, I mean, AFK system is not generating any lags at all.
