### ISSUE TITLE
PlaceholderAPI update.

### ISSUE THREAD

**Issue by Weasel-Beans** [Kugge/BestViewDistance#29]
08.05 06:52:39 [Server] WARN BestViewDistance is currently using a deprecated method to hook into PlaceholderAPI. This will be disabled after the next update. Please consult [Lxct] and urge them to update it ASAP.

I believe PAPI has already been updated, so BestViewDistance is probably not compatible with the new version.

**Comment by smellyonionman** [comment]
It's not.  BVD is the last plugin on my server to update before we can use the new PAPI. = ( Eventually though!

**Comment by sofianedjerbi** [comment]
Fixed.
