### ISSUE TITLE
1.13.2 error. :D

### ISSUE THREAD

**Issue by TheIntelloBox** [Kugge/BestViewDistance#6]
Hello ! 🗡 

I have this error in the console:
https://hastebin.com/usijabukom.sql

Thanks for fixing it or helping me ! :D 
TheIntelloBox. :D

**Comment by Lxct** [comment]
I cannot see what is written into this hastebin, can you copy/paste this error here ?
If you want to make a bug-report on discord : [https://discord.gg/fDCc8xG](https://discord.gg/fDCc8xG)
(PS (French) : Si tu parles francais, vas-y :p )

**Comment by Lxct** [comment]
The error was [https://pastebin.com/W9kgZkSC](https://pastebin.com/W9kgZkSC)
Caused by citizen.
