### ISSUE TITLE
Latest version has a bug causing some players to be invisible

### ISSUE THREAD

**Issue by axemwa** [Kugge/BestViewDistance#7]
**Describe the bug**

Latest version has a bug causing some playewrs to be invisible

**To Reproduce**

*1. Join server*
*2. Join server with a 2nd account and 2nd client*
*3. Use one of the accounts to look at the other player vice versa*
*4. See bug*

**Expected behavior**

To not make any players invisible

**Comment by MrSpock78** [comment]
Happens to me after relogging near another player. I wasn´t able to see him until I ported away and back again.

**Comment by axemwa** [comment]
ive removed the plugin for now so players can't abuse it

**Comment by HauserGrim** [comment]
+1
Fix this please!

**Comment by mibby** [comment]
Is this issue still present? Seems quite serious. :( Hopefully @Lxct can look into it to get it fixed.

**Comment by axemwa** [comment]
yeah nothings changed, miss usin the plugin

**Comment by axemwa** [comment]
yeah nothings changed, I miss usin the plugin

**Comment by graywolf336** [comment]
Just letting everyone here know, I have forked this plugin and fixed this issue along with several others.

https://github.com/graywolf336/BestViewDistance

Should @Lxct come back and be active again, I'll discuss with him on getting things merged if he plans to maintain it further.

**Comment by sofianedjerbi** [comment]
Fixed in 337dde5

**Comment by axemwa** [comment]
When try downloading latest passed dev build and use it the view distance is always set to 4 and doesn't adjust accordingly. I have view distance in spigot.yml set to 3, that's correct right?

**Comment by sofianedjerbi** [comment]
That's okay, but it shouldn't be stuck on 4. Which dev build are you using ? Can I see your server ?

**Comment by axemwa** [comment]
I'm using this version 
https://ci.codemc.org/job/Kugge/job/BestViewDistance/40/
And I have view distance in spigot.yml set to 3 we're still supposed to do that right?
Config is set to default
I'm seeing this below when I join and type /vdist
![image](https://user-images.githubusercontent.com/37608633/61166868-573e4980-a574-11e9-9c37-f1b436d6b88a.png)
Also you can join the server if you wish, the address is civcraft.servegame.com

**Comment by sofianedjerbi** [comment]
View distance in spigot.yml is fine, however, it seems that your internet connection doesn't support a view distance over 4. Please send us your ping and config.yml file

**Comment by axemwa** [comment]
Ping varies from 0 - 10
Doesn't have to do with my internet cause the ping is low and it's worked fine in the past in previous stable versions (longer than a month ago) of the plugin and I had the same internet then so it can't be that. I'll keep trying.

**Comment by axemwa** [comment]
And the config is the default one that's generated

**Comment by axemwa** [comment]
Version on spigotmc seems to be working fine though :)

**Comment by sofianedjerbi** [comment]
(If ping = 0 you should set up safe ping on 0 too)

**Comment by axemwa** [comment]
Ah thank you I think this has fixed it as I would normally be testing it while at 0 ping whether on localhost or from the server address itself.
Everything seems to be ok now I'd probably suggest having it set to 0 by default in config though instead of 1 for future versions since server owners who are testing it will more than likely have a ping of 0.

**Comment by axemwa** [comment]
afk view distance doesn't seem to apply though and neither does teleport view distance?
